/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const VideoVideoNidLazyImport = createFileRoute('/video/$videoNid')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const VideoVideoNidLazyRoute = VideoVideoNidLazyImport.update({
  path: '/video/$videoNid',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/video/$videoNid.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/video/$videoNid': {
      id: '/video/$videoNid'
      path: '/video/$videoNid'
      fullPath: '/video/$videoNid'
      preLoaderRoute: typeof VideoVideoNidLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  VideoVideoNidLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/video/$videoNid"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/video/$videoNid": {
      "filePath": "video/$videoNid.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
