/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ManageTagIndexImport } from './routes/manage/tag/index'
import { Route as ManageTagCateIndexImport } from './routes/manage/tag/cate/index'

// Create Virtual Routes

const VideoVideoNidLazyImport = createFileRoute('/video/$videoNid')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VideoVideoNidLazyRoute = VideoVideoNidLazyImport.update({
  path: '/video/$videoNid',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/video/$videoNid.lazy').then((d) => d.Route),
)

const ManageTagIndexRoute = ManageTagIndexImport.update({
  path: '/manage/tag/',
  getParentRoute: () => rootRoute,
} as any)

const ManageTagCateIndexRoute = ManageTagCateIndexImport.update({
  path: '/manage/tag/cate/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/video/$videoNid': {
      id: '/video/$videoNid'
      path: '/video/$videoNid'
      fullPath: '/video/$videoNid'
      preLoaderRoute: typeof VideoVideoNidLazyImport
      parentRoute: typeof rootRoute
    }
    '/manage/tag/': {
      id: '/manage/tag/'
      path: '/manage/tag'
      fullPath: '/manage/tag'
      preLoaderRoute: typeof ManageTagIndexImport
      parentRoute: typeof rootRoute
    }
    '/manage/tag/cate/': {
      id: '/manage/tag/cate/'
      path: '/manage/tag/cate'
      fullPath: '/manage/tag/cate'
      preLoaderRoute: typeof ManageTagCateIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  VideoVideoNidLazyRoute,
  ManageTagIndexRoute,
  ManageTagCateIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/video/$videoNid",
        "/manage/tag/",
        "/manage/tag/cate/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/video/$videoNid": {
      "filePath": "video/$videoNid.lazy.tsx"
    },
    "/manage/tag/": {
      "filePath": "manage/tag/index.tsx"
    },
    "/manage/tag/cate/": {
      "filePath": "manage/tag/cate/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
